### ISSUE TITLE
LoadError: cannot load such file -- action_view on IRuby

### ISSUE THREAD

**Issue by brodock** [Shekharrajak/daru-data_tables#26]
Looks like this is a different issue, but related to #2. The issue is that it looks like there is code depending on Rails, that shouldn't be loaded when in IRuby.

This is the error I get: 

```
LoadError: cannot load such file -- action_view
/Users/brodock/.rvm/gems/ruby-2.5.3/gems/daru-data_tables-0.3.5/lib/daru/data_tables/display/display.rb:5:in `require'
/Users/brodock/.rvm/gems/ruby-2.5.3/gems/daru-data_tables-0.3.5/lib/daru/data_tables/display/display.rb:5:in `<top (required)>'
/Users/brodock/.rvm/gems/ruby-2.5.3/gems/daru-data_tables-0.3.5/lib/daru/data_tables.rb:4:in `require'
/Users/brodock/.rvm/gems/ruby-2.5.3/gems/daru-data_tables-0.3.5/lib/daru/data_tables.rb:4:in `<top (required)>'
```

**Comment by Shekharrajak** [comment]
Sorry I missed this issue notification. It look like `action_view` gem is not installed in your system. PLease install using `gem install action_view`.
